-- AlterTable
ALTER TABLE "Debt" ADD COLUMN     "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "type" SET DEFAULT '';

-- AlterTable
ALTER TABLE "Member" ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "address" SET DEFAULT '',
ALTER COLUMN "phone" SET DEFAULT '';

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "description" SET DEFAULT '',
ALTER COLUMN "type" SET DEFAULT '';

-- AlterTable
ALTER TABLE "Transaction" ADD COLUMN     "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
